# -*- coding: utf-8 -*-
"""exercicio_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12VZKKPd2XuOZChI_u8WY9i7oNMSue30J

# Imports
"""

import pandas as pd

"""# Loading Files"""

df = pd.read_csv ('/content/sample_data/kc_house_data.csv')

"""# Anserwering Questions

## 1. Quantas casas estão disponíveis para compra?
 R: 21.613 casas
"""

df.shape

"""## 2. Quantos atributos as casas possuem?
 R:16 atributos
"""

df.columns

"""## 3. Quais são os atributos das casas?
 R: bedrooms, bathrooms, sqft_living, sqft_lot, floors,waterfront, view, condition ,grade, sqft_above,sqft_basement, yr_built, yr_renovated, zipcode, sqft_living15, sqft_lot15
"""

df.columns

"""## 4. Qual a casa mais cara (casa com o maior valor de venda)
R: Casa com o ID:6762700020

---


"""

df.sort_values ('price',ascending=False)

"""## 5. Qual a casa com o maior número de quartos?
R: Casa ID 2402100895
"""

df.sort_values('bedrooms', ascending=False)

"""## 6. Qual a soma total de quartos do conjunto de dados?
R:72.854 bedrooms
"""

df[['bedrooms']].sum()

"""## 7. Quantas casas possuem 2 banheiros?
R:1930 casas
"""

two_bath_house = df.loc[df['bathrooms'] == 2]
two_bath_house.shape

"""## 8. Qual o  preço médio de todas as casas no conjunto dado?
R:A média do preço das casas é $540.088.14.
"""

df[['price']].mean()

"""## 9. Qual o preço médio de casas com 2 banheiros?
R: A média do preço das casas com dois banheiros é  $ 457.889.71.
"""

two_bath_house[['price']].mean()

"""## 10. Qual o preço mínimo entre as casas com 3 quartos?
R:Das casas com 3 quartos, a mais barata custa $82.000.
"""

tree_bedr_house = df.loc[df['bedrooms'] == 3]
tree_bedr_house.sort_values('price', ascending=True)

"""## 11. Quantas casas possuem mais de 300 metros quadrados na sala de estar?
R:1947 casas
"""

more_300_m2 = df.loc[df['sqft_living'] > 300]
more_300_m2



"""## 12. Quantas casas tem mais de 2 andares
R: 782 casas

"""

df.loc[df['floors'] > 2].shape[0]

"""## 13. Quantas casas tem vista para o mar?
R:163 casas tem vista para o mar
"""

waterfront_houses = df.loc[df['waterfront'] == 1]

"""## 14. Das casas com vista pro mar, quantas tem 3 quartos?
R: 64 casas
"""

waterfront_houses.loc[waterfront_houses['bedrooms'] == 3].shape[0]

"""## 15. Das casas com mais de 300 metros quadrados de sala de estar quantas tem mais de 2 banheiros?
R: 1899 casas

"""

more_300_m2.loc[more_300_m2['bathrooms'] > 2].sort_values('bathrooms', ascending=True)